spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/olleu
    username: root
    password: olleu2023

  jpa:
    database: mysql
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: true
    hibernate:
      ddl-auto: update


jwt:
  secret: YmJhbGRhZWJ1bWludGVsbGlqaGliaXNjdXNvbGxldXByb2plY3Q=
  access-token-expiration-time: 21600
  refresh-token-expiration-time: 604800
