spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/olleu
    username: root
    password: olleu2023

  jpa:
    database: mysql
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: olleu159@gamil.com
    password: mqactqwmencpeuoa
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    default-encoding: UTF-8
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: true
